site_name: LFO Calculator Project
# site_description:
site_author: rc-ms
# google_analytics:
# remote_branch: for gh-deploy to GithubPages
# remote_name: for gh-deploy to Github Pages
docs_dir: "docs"
repo_url: https://github.com/lfo-calculator/site
nav:
  - Home: index.md
  - Resources: 
    - Overview: Resources.md
    - Determining "Ability to Pay": Ability_to_pay.md
  - FAQ: FAQ.md
  - Help: Help.md
  - Use the LFO Calculator: https://beta.lfocalculator.org
  - LFO 2.0: 
    - LFO 2.0: LFO2dot0.md
    - Hawaii Prototype effort notes: Hawaii_prototype.md
    - Hawaii Legal notes: Hawaii_legal_notes.md
    - Hawaii Vue front end: https://lfo-calculator.github.io/vue-hi/

plugins:
  - search
theme:
  name: material
#  custom_dir: overrides
#  favicon: images/favicon.ico
#  logo: images/electionguard-logo.png
  font:
    text: Segoe UI
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.instant
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
