site_name: LFO Calculator
# site_description:
# site_author: Microsoft
# google_analytics:
# remote_branch: for gh-deploy to GithubPages
# remote_name: for gh-deploy to Github Pages
# copyright: "© Microsoft 2021"
docs_dir: "docs"
repo_url: https://github.com/lfo-calculator/site
nav:
  - Home: index.md
  - About: Introduction.md

plugins:
  - search
theme:
  name: material
#  custom_dir: overrides
#  favicon: images/favicon.ico
#  logo: images/electionguard-logo.png
  font:
    text: Segoe UI
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.instant
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
